Repository h2oai/h2o4gpu, pull requests merged in 2018-03, with the labels that each got.

#489 Modify predict method in R to account for probabilities and update predict_proba in Py API
  src/interface_py/h2o4gpu/solvers/daal_solver/svd.py
  src/interface_py/h2o4gpu/solvers/elastic_net.py
  src/interface_py/h2o4gpu/solvers/xgboost.py
  src/interface_r/R/model.R
  src/interface_r/man/predict.h2o4gpu_model.Rd
Labels: R

#492 Fixes #436
  src/cpu/h2o4gpuglm.cpp
  src/gpu/h2o4gpuglm.cu
  src/include/h2o4gpuglm.h
  src/interface_py/h2o4gpu/solvers/elastic_net.py
Labels: bug

#494 Fixes #438
  src/interface_py/h2o4gpu/solvers/xgboost.py
Labels: bug

#500 Fix version number in Python
  src/interface_py/h2o4gpu/__init__.base.py
Labels: bug, priority: high

#461 R package vignette (tutorial)
  src/interface_r/DESCRIPTION
  src/interface_r/vignettes/getting_started.Rmd
Labels: R, community, documentation

#519 Version bump after v0.2.0 release
  README.md
  make/version.mk
  src/interface_py/h2o4gpu/__init__.base.py
  src/interface_r/DESCRIPTION
Labels: build
